config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :formal_educations
  resources :bloods
  resources :sexes
  resources :married_statuses
  resources :job_experiences
  resources :achievements
  resources :scientific_works
  resources :organizations
  resources :travellings
  resources :family_relations
  resources :education_levels
  resources :families
  resources :language_levels
  resources :languages
  resources :profiles
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users

  resources :users



end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :profile
end

app/models/blood.rb
class Blood < ApplicationRecord
end

app/models/education_level.rb
class EducationLevel < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :profile
end

app/models/family_relation.rb
class FamilyRelation < ApplicationRecord
end

app/models/formal_education.rb
class FormalEducation < ApplicationRecord
  belongs_to :profile
end

app/models/job_experience.rb
class JobExperience < ApplicationRecord
  belongs_to :profile
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :profile
end

app/models/language_level.rb
class LanguageLevel < ApplicationRecord
end

app/models/married_status.rb
class MarriedStatus < ApplicationRecord
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_many :languages, inverse_of: :profile
	has_many :families, inverse_of: :profile
	has_many :travellings, inverse_of: :profile
	has_many :organizations, inverse_of: :profile
	has_many :scientific_works, inverse_of: :profile
	has_many :achievements, inverse_of: :profile
	has_many :job_experiences, inverse_of: :profile
	has_many :formal_educations, inverse_of: :profile
	has_many :trainings, inverse_of: :profile



	accepts_nested_attributes_for :languages, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :families, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :travellings, reject_if: proc { |attributes| attributes['country'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :organizations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :scientific_works, reject_if: proc { |attributes| attributes['title'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :achievements, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :job_experiences, reject_if: proc { |attributes| attributes['company_name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :formal_educations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :trainings, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	#accepts_nested_attributes_for :languages, allow_destroy: true

	#reject_if: proc { |attributes| attributes['title'].blank? }


end

app/models/scientific_work.rb
class ScientificWork < ApplicationRecord
  belongs_to :profile
end

app/models/sex.rb
class Sex < ApplicationRecord
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :profile
end

app/models/travelling.rb
class Travelling < ApplicationRecord
  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile 
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  after_create :create_profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def to_param
    name
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:name, :organizer, :location, :year, :certificate, :notes, :profile_id)
    end
end

app/helpers/bloods_helper.rb
module BloodsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sexes_helper.rb
module SexesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_for(training) do |f| %>
  <% if training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :organizer %>
    <%= f.text_field :organizer %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.date_select :year %>
  </div>

  <div class="field">
    <%= f.label :certificate %>
    <%= f.text_field :certificate %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :profile_id %>
    <%= f.text_field :profile_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Organizer</th>
      <th>Location</th>
      <th>Year</th>
      <th>Certificate</th>
      <th>Notes</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.name %></td>
        <td><%= training.organizer %></td>
        <td><%= training.location %></td>
        <td><%= training.year %></td>
        <td><%= training.certificate %></td>
        <td><%= training.notes %></td>
        <td><%= training.profile %></td>
        <td><%= link_to 'Show', training %></td>
        <td><%= link_to 'Edit', edit_training_path(training) %></td>
        <td><%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training', new_training_path %>

app/views/trainings/new.html.erb
<h1>New Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @training.name %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @training.organizer %>
</p>

<p>
  <strong>Location:</strong>
  <%= @training.location %>
</p>

<p>
  <strong>Year:</strong>
  <%= @training.year %>
</p>

<p>
  <strong>Certificate:</strong>
  <%= @training.certificate %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @training.notes %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @training.profile %>
</p>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>