config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :formal_educations
  resources :bloods
  resources :sexes
  resources :married_statuses
  resources :job_experiences
  resources :achievements
  resources :scientific_works
  resources :organizations
  resources :travellings
  resources :family_relations
  resources :education_levels
  resources :families
  resources :language_levels
  resources :languages
  resources :profiles
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users

  resources :users



end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :profile
end

app/models/blood.rb
class Blood < ApplicationRecord
end

app/models/education_level.rb
class EducationLevel < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :profile
end

app/models/family_relation.rb
class FamilyRelation < ApplicationRecord
end

app/models/formal_education.rb
class FormalEducation < ApplicationRecord
  belongs_to :profile
end

app/models/job_experience.rb
class JobExperience < ApplicationRecord
  belongs_to :profile
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :profile
end

app/models/language_level.rb
class LanguageLevel < ApplicationRecord
end

app/models/married_status.rb
class MarriedStatus < ApplicationRecord
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_many :languages, inverse_of: :profile
	has_many :families, inverse_of: :profile
	has_many :travellings, inverse_of: :profile
	has_many :organizations, inverse_of: :profile
	has_many :scientific_works, inverse_of: :profile
	has_many :achievements, inverse_of: :profile
	has_many :job_experiences, inverse_of: :profile
	has_many :formal_educations, inverse_of: :profile
	has_many :trainings, inverse_of: :profile



	accepts_nested_attributes_for :languages, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :families, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :travellings, reject_if: proc { |attributes| attributes['country'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :organizations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :scientific_works, reject_if: proc { |attributes| attributes['title'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :achievements, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :job_experiences, reject_if: proc { |attributes| attributes['company_name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :formal_educations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :trainings, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	#accepts_nested_attributes_for :languages, allow_destroy: true

	#reject_if: proc { |attributes| attributes['title'].blank? }


end

app/models/scientific_work.rb
class ScientificWork < ApplicationRecord
  belongs_to :profile
end

app/models/sex.rb
class Sex < ApplicationRecord
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :profile
end

app/models/travelling.rb
class Travelling < ApplicationRecord
  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile 
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  after_create :create_profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def to_param
    name
  end

end

app/controllers/job_experiences_controller.rb
class JobExperiencesController < ApplicationController
  before_action :set_job_experience, only: [:show, :edit, :update, :destroy]

  # GET /job_experiences
  # GET /job_experiences.json
  def index
    @job_experiences = JobExperience.all
  end

  # GET /job_experiences/1
  # GET /job_experiences/1.json
  def show
  end

  # GET /job_experiences/new
  def new
    @job_experience = JobExperience.new
  end

  # GET /job_experiences/1/edit
  def edit
  end

  # POST /job_experiences
  # POST /job_experiences.json
  def create
    @job_experience = JobExperience.new(job_experience_params)

    respond_to do |format|
      if @job_experience.save
        format.html { redirect_to @job_experience, notice: 'Job experience was successfully created.' }
        format.json { render :show, status: :created, location: @job_experience }
      else
        format.html { render :new }
        format.json { render json: @job_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_experiences/1
  # PATCH/PUT /job_experiences/1.json
  def update
    respond_to do |format|
      if @job_experience.update(job_experience_params)
        format.html { redirect_to @job_experience, notice: 'Job experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_experience }
      else
        format.html { render :edit }
        format.json { render json: @job_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_experiences/1
  # DELETE /job_experiences/1.json
  def destroy
    @job_experience.destroy
    respond_to do |format|
      format.html { redirect_to job_experiences_url, notice: 'Job experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_experience
      @job_experience = JobExperience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_experience_params
      params.require(:job_experience).permit(:company_name, :company_address, :company_phone, :job_title, :start_date, :end_date, :job_description, :reason_of_resignation, :profile_id)
    end
end

app/helpers/bloods_helper.rb
module BloodsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/job_experiences_helper.rb
module JobExperiencesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sexes_helper.rb
module SexesHelper
end

app/views/job_experiences/_form.html.erb
<%= form_for(job_experience) do |f| %>
  <% if job_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_experience.errors.count, "error") %> prohibited this job_experience from being saved:</h2>

      <ul>
      <% job_experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>

  <div class="field">
    <%= f.label :company_address %>
    <%= f.text_field :company_address %>
  </div>

  <div class="field">
    <%= f.label :company_phone %>
    <%= f.text_field :company_phone %>
  </div>

  <div class="field">
    <%= f.label :job_title %>
    <%= f.text_field :job_title %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <%= f.label :job_description %>
    <%= f.text_area :job_description %>
  </div>

  <div class="field">
    <%= f.label :reason_of_resignation %>
    <%= f.text_area :reason_of_resignation %>
  </div>

  <div class="field">
    <%= f.label :profile_id %>
    <%= f.text_field :profile_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_experiences/edit.html.erb
<h1>Editing Job Experience</h1>

<%= render 'form', job_experience: @job_experience %>

<%= link_to 'Show', @job_experience %> |
<%= link_to 'Back', job_experiences_path %>

app/views/job_experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Experiences</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company address</th>
      <th>Company phone</th>
      <th>Job title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Job description</th>
      <th>Reason of resignation</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_experiences.each do |job_experience| %>
      <tr>
        <td><%= job_experience.company_name %></td>
        <td><%= job_experience.company_address %></td>
        <td><%= job_experience.company_phone %></td>
        <td><%= job_experience.job_title %></td>
        <td><%= job_experience.start_date %></td>
        <td><%= job_experience.end_date %></td>
        <td><%= job_experience.job_description %></td>
        <td><%= job_experience.reason_of_resignation %></td>
        <td><%= job_experience.profile %></td>
        <td><%= link_to 'Show', job_experience %></td>
        <td><%= link_to 'Edit', edit_job_experience_path(job_experience) %></td>
        <td><%= link_to 'Destroy', job_experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job Experience', new_job_experience_path %>

app/views/job_experiences/new.html.erb
<h1>New Job Experience</h1>

<%= render 'form', job_experience: @job_experience %>

<%= link_to 'Back', job_experiences_path %>

app/views/job_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @job_experience.company_name %>
</p>

<p>
  <strong>Company address:</strong>
  <%= @job_experience.company_address %>
</p>

<p>
  <strong>Company phone:</strong>
  <%= @job_experience.company_phone %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @job_experience.job_title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @job_experience.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @job_experience.end_date %>
</p>

<p>
  <strong>Job description:</strong>
  <%= @job_experience.job_description %>
</p>

<p>
  <strong>Reason of resignation:</strong>
  <%= @job_experience.reason_of_resignation %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @job_experience.profile %>
</p>

<%= link_to 'Edit', edit_job_experience_path(@job_experience) %> |
<%= link_to 'Back', job_experiences_path %>