config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :formal_educations
  resources :bloods
  resources :sexes
  resources :married_statuses
  resources :job_experiences
  resources :achievements
  resources :scientific_works
  resources :organizations
  resources :travellings
  resources :family_relations
  resources :education_levels
  resources :families
  resources :language_levels
  resources :languages
  resources :profiles
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users

  resources :users



end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :profile
end

app/models/blood.rb
class Blood < ApplicationRecord
end

app/models/education_level.rb
class EducationLevel < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :profile
end

app/models/family_relation.rb
class FamilyRelation < ApplicationRecord
end

app/models/formal_education.rb
class FormalEducation < ApplicationRecord
  belongs_to :profile
end

app/models/job_experience.rb
class JobExperience < ApplicationRecord
  belongs_to :profile
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :profile
end

app/models/language_level.rb
class LanguageLevel < ApplicationRecord
end

app/models/married_status.rb
class MarriedStatus < ApplicationRecord
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_many :languages, inverse_of: :profile
	has_many :families, inverse_of: :profile
	has_many :travellings, inverse_of: :profile
	has_many :organizations, inverse_of: :profile
	has_many :scientific_works, inverse_of: :profile
	has_many :achievements, inverse_of: :profile
	has_many :job_experiences, inverse_of: :profile
	has_many :formal_educations, inverse_of: :profile
	has_many :trainings, inverse_of: :profile



	accepts_nested_attributes_for :languages, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :families, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :travellings, reject_if: proc { |attributes| attributes['country'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :organizations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :scientific_works, reject_if: proc { |attributes| attributes['title'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :achievements, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :job_experiences, reject_if: proc { |attributes| attributes['company_name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :formal_educations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :trainings, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	#accepts_nested_attributes_for :languages, allow_destroy: true

	#reject_if: proc { |attributes| attributes['title'].blank? }


end

app/models/scientific_work.rb
class ScientificWork < ApplicationRecord
  belongs_to :profile
end

app/models/sex.rb
class Sex < ApplicationRecord
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :profile
end

app/models/travelling.rb
class Travelling < ApplicationRecord
  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile 
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  after_create :create_profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def to_param
    name
  end

end

app/controllers/family_relations_controller.rb
class FamilyRelationsController < ApplicationController
  before_action :set_family_relation, only: [:show, :edit, :update, :destroy]

  # GET /family_relations
  # GET /family_relations.json
  def index
    @family_relations = FamilyRelation.all
  end

  # GET /family_relations/1
  # GET /family_relations/1.json
  def show
  end

  # GET /family_relations/new
  def new
    @family_relation = FamilyRelation.new
  end

  # GET /family_relations/1/edit
  def edit
  end

  # POST /family_relations
  # POST /family_relations.json
  def create
    @family_relation = FamilyRelation.new(family_relation_params)

    respond_to do |format|
      if @family_relation.save
        format.html { redirect_to @family_relation, notice: 'Family relation was successfully created.' }
        format.json { render :show, status: :created, location: @family_relation }
      else
        format.html { render :new }
        format.json { render json: @family_relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /family_relations/1
  # PATCH/PUT /family_relations/1.json
  def update
    respond_to do |format|
      if @family_relation.update(family_relation_params)
        format.html { redirect_to @family_relation, notice: 'Family relation was successfully updated.' }
        format.json { render :show, status: :ok, location: @family_relation }
      else
        format.html { render :edit }
        format.json { render json: @family_relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_relations/1
  # DELETE /family_relations/1.json
  def destroy
    @family_relation.destroy
    respond_to do |format|
      format.html { redirect_to family_relations_url, notice: 'Family relation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_relation
      @family_relation = FamilyRelation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_relation_params
      params.require(:family_relation).permit(:name)
    end
end

app/helpers/bloods_helper.rb
module BloodsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/family_relations_helper.rb
module FamilyRelationsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sexes_helper.rb
module SexesHelper
end

app/views/family_relations/_form.html.erb
<%= form_for(family_relation) do |f| %>
  <% if family_relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family_relation.errors.count, "error") %> prohibited this family_relation from being saved:</h2>

      <ul>
      <% family_relation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/family_relations/edit.html.erb
<h1>Editing Family Relation</h1>

<%= render 'form', family_relation: @family_relation %>

<%= link_to 'Show', @family_relation %> |
<%= link_to 'Back', family_relations_path %>

app/views/family_relations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Family Relations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @family_relations.each do |family_relation| %>
      <tr>
        <td><%= family_relation.name %></td>
        <td><%= link_to 'Show', family_relation %></td>
        <td><%= link_to 'Edit', edit_family_relation_path(family_relation) %></td>
        <td><%= link_to 'Destroy', family_relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family Relation', new_family_relation_path %>

app/views/family_relations/new.html.erb
<h1>New Family Relation</h1>

<%= render 'form', family_relation: @family_relation %>

<%= link_to 'Back', family_relations_path %>

app/views/family_relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @family_relation.name %>
</p>

<%= link_to 'Edit', edit_family_relation_path(@family_relation) %> |
<%= link_to 'Back', family_relations_path %>