config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :formal_educations
  resources :bloods
  resources :sexes
  resources :married_statuses
  resources :job_experiences
  resources :achievements
  resources :scientific_works
  resources :organizations
  resources :travellings
  resources :family_relations
  resources :education_levels
  resources :families
  resources :language_levels
  resources :languages
  resources :profiles
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users

  resources :users



end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :profile
end

app/models/blood.rb
class Blood < ApplicationRecord
end

app/models/education_level.rb
class EducationLevel < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :profile
end

app/models/family_relation.rb
class FamilyRelation < ApplicationRecord
end

app/models/formal_education.rb
class FormalEducation < ApplicationRecord
  belongs_to :profile
end

app/models/job_experience.rb
class JobExperience < ApplicationRecord
  belongs_to :profile
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :profile
end

app/models/language_level.rb
class LanguageLevel < ApplicationRecord
end

app/models/married_status.rb
class MarriedStatus < ApplicationRecord
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_many :languages, inverse_of: :profile
	has_many :families, inverse_of: :profile
	has_many :travellings, inverse_of: :profile
	has_many :organizations, inverse_of: :profile
	has_many :scientific_works, inverse_of: :profile
	has_many :achievements, inverse_of: :profile
	has_many :job_experiences, inverse_of: :profile
	has_many :formal_educations, inverse_of: :profile
	has_many :trainings, inverse_of: :profile



	accepts_nested_attributes_for :languages, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :families, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :travellings, reject_if: proc { |attributes| attributes['country'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :organizations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :scientific_works, reject_if: proc { |attributes| attributes['title'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :achievements, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :job_experiences, reject_if: proc { |attributes| attributes['company_name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :formal_educations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :trainings, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	#accepts_nested_attributes_for :languages, allow_destroy: true

	#reject_if: proc { |attributes| attributes['title'].blank? }


end

app/models/scientific_work.rb
class ScientificWork < ApplicationRecord
  belongs_to :profile
end

app/models/sex.rb
class Sex < ApplicationRecord
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :profile
end

app/models/travelling.rb
class Travelling < ApplicationRecord
  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile 
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  after_create :create_profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def to_param
    name
  end

end

app/controllers/education_levels_controller.rb
class EducationLevelsController < ApplicationController
  before_action :set_education_level, only: [:show, :edit, :update, :destroy]

  # GET /education_levels
  # GET /education_levels.json
  def index
    @education_levels = EducationLevel.all
  end

  # GET /education_levels/1
  # GET /education_levels/1.json
  def show
  end

  # GET /education_levels/new
  def new
    @education_level = EducationLevel.new
  end

  # GET /education_levels/1/edit
  def edit
  end

  # POST /education_levels
  # POST /education_levels.json
  def create
    @education_level = EducationLevel.new(education_level_params)

    respond_to do |format|
      if @education_level.save
        format.html { redirect_to @education_level, notice: 'Education level was successfully created.' }
        format.json { render :show, status: :created, location: @education_level }
      else
        format.html { render :new }
        format.json { render json: @education_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /education_levels/1
  # PATCH/PUT /education_levels/1.json
  def update
    respond_to do |format|
      if @education_level.update(education_level_params)
        format.html { redirect_to @education_level, notice: 'Education level was successfully updated.' }
        format.json { render :show, status: :ok, location: @education_level }
      else
        format.html { render :edit }
        format.json { render json: @education_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /education_levels/1
  # DELETE /education_levels/1.json
  def destroy
    @education_level.destroy
    respond_to do |format|
      format.html { redirect_to education_levels_url, notice: 'Education level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_level
      @education_level = EducationLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_level_params
      params.require(:education_level).permit(:name)
    end
end

app/helpers/bloods_helper.rb
module BloodsHelper
end

app/helpers/education_levels_helper.rb
module EducationLevelsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sexes_helper.rb
module SexesHelper
end

app/views/education_levels/_form.html.erb
<%= form_for(education_level) do |f| %>
  <% if education_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education_level.errors.count, "error") %> prohibited this education_level from being saved:</h2>

      <ul>
      <% education_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/education_levels/edit.html.erb
<h1>Editing Education Level</h1>

<%= render 'form', education_level: @education_level %>

<%= link_to 'Show', @education_level %> |
<%= link_to 'Back', education_levels_path %>

app/views/education_levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Education Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @education_levels.each do |education_level| %>
      <tr>
        <td><%= education_level.name %></td>
        <td><%= link_to 'Show', education_level %></td>
        <td><%= link_to 'Edit', edit_education_level_path(education_level) %></td>
        <td><%= link_to 'Destroy', education_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education Level', new_education_level_path %>

app/views/education_levels/new.html.erb
<h1>New Education Level</h1>

<%= render 'form', education_level: @education_level %>

<%= link_to 'Back', education_levels_path %>

app/views/education_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @education_level.name %>
</p>

<%= link_to 'Edit', edit_education_level_path(@education_level) %> |
<%= link_to 'Back', education_levels_path %>